/**
 * POST /api/cases/[id]/audio-upload-url
 *
 * Returns a signed Supabase Storage upload URL so the browser can PUT the
 * audio file DIRECTLY to Supabase, bypassing Vercel's 4.5 MB serverless
 * function payload limit. After the client finishes the direct PUT, it
 * calls /api/cases/[id]/post-call with `{ audio_path: <returned-path> }`
 * which generates a signed READ URL server-side and persists it into
 * lead_cases.audio_blob_url for Deepgram.
 *
 * Why this exists:
 *   The original /post-call route accepts multipart audio uploads. That
 *   works in dev (Next.js dev server has no payload cap) but fails on
 *   Vercel prod with FUNCTION_PAYLOAD_TOO_LARGE for any audio > 4.5 MB.
 *   Real sales calls are typically 15-30 minutes = 100+ MB — multipart
 *   into a serverless function is structurally wrong for production.
 *
 * Body (JSON):
 *   filename:      string  (e.g. "call.wav") — used to derive extension
 *   content_type?: string  (defaults to "audio/wav")
 *
 * Returns:
 *   {
 *     signed_upload_url: string,   // PUT the file bytes here
 *     path:              string,   // bucket-internal path; pass to /post-call as audio_path
 *     expires_in:        number,   // upload-URL TTL in seconds (5 min)
 *   }
 *
 * Auth:
 *   No BDA approval code required — uploading raw audio is not a
 *   lead-facing action. Per R04, only lead-facing routes are gated.
 *   The case-id in the URL is the only access control: callers must
 *   already know the case-id (a UUID) which is generated by /api/leads.
 */
import { NextResponse } from "next/server";
import { supabaseServer } from "@/lib/supabase";
import { log } from "@/lib/log";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const AUDIO_BUCKET = process.env.SUPABASE_BUCKET_AUDIO || "scaler-sales-audio";
const UPLOAD_URL_TTL_SECONDS = 5 * 60; // 5 min — enough for any real upload

interface UploadUrlBody {
  filename?: string;
  content_type?: string;
}

const ALLOWED_STATES = new Set(["nudge_scheduled", "nudge_sent", "received", "failed"]);

function extFromName(filename: string, contentType?: string): string {
  const lower = filename.toLowerCase();
  if (lower.endsWith(".wav")) return "wav";
  if (lower.endsWith(".mp3")) return "mp3";
  if (lower.endsWith(".m4a")) return "m4a";
  if (lower.endsWith(".ogg")) return "ogg";
  if (contentType?.includes("wav")) return "wav";
  if (contentType?.includes("mpeg") || contentType?.includes("mp3")) return "mp3";
  if (contentType?.includes("m4a") || contentType?.includes("mp4")) return "m4a";
  return "bin";
}

export async function POST(req: Request, { params }: { params: { id: string } }) {
  const caseId = params.id;
  const component = "audio_upload_url";
  if (!caseId) return NextResponse.json({ error: "missing case id" }, { status: 400 });

  const body = (await req.json().catch(() => ({}))) as UploadUrlBody;
  const filename = body.filename?.trim() || "audio.wav";
  const contentType = body.content_type?.trim() || "audio/wav";

  const supabase = supabaseServer();

  // Verify case exists and is in a pre-ingest state.
  const { data: row, error: fetchErr } = await supabase
    .from("lead_cases")
    .select("id, state")
    .eq("id", caseId)
    .single();
  if (fetchErr || !row) {
    return NextResponse.json(
      { error: `case not found: ${fetchErr?.message ?? "no row"}`, case_id: caseId },
      { status: 404 }
    );
  }
  if (!ALLOWED_STATES.has(row.state as string)) {
    return NextResponse.json(
      {
        error: `case is in state '${row.state}' — past the audio-upload step`,
        case_id: caseId,
      },
      { status: 409 }
    );
  }

  // Generate a deterministic-ish path. Timestamp suffix makes re-uploads
  // distinguishable. The /post-call route will sign a READ URL for whatever
  // path the caller passes back via audio_path.
  const ext = extFromName(filename, contentType);
  const path = `cases/${caseId}/source-${Date.now()}.${ext}`;

  const { data: signed, error: signErr } = await supabase.storage
    .from(AUDIO_BUCKET)
    .createSignedUploadUrl(path);
  if (signErr || !signed) {
    await log({
      case_id: caseId,
      task_id: "audio-upload-url",
      component,
      level: "ERROR",
      event: "create_signed_upload_url_failed",
      error_message: signErr?.message ?? "no signed url",
    });
    return NextResponse.json(
      {
        error: `failed to create signed upload url: ${signErr?.message ?? "unknown"}`,
        case_id: caseId,
      },
      { status: 500 }
    );
  }

  await log({
    case_id: caseId,
    task_id: "audio-upload-url",
    component,
    event: "signed_upload_url_issued",
    payload: { bucket: AUDIO_BUCKET, path, content_type: contentType },
  });

  return NextResponse.json({
    case_id: caseId,
    signed_upload_url: signed.signedUrl,
    path,
    expires_in: UPLOAD_URL_TTL_SECONDS,
    content_type: contentType,
  });
}
